
#spring.datasource.url=jdbc:postgresql://localhost:3303/rcnv
#spring.datasource.username=postgres
#spring.datasource.password=Mayur@123
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/rcnv_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
file.upload-dir=uploads

app.cors.allowed-origins=http://localhost:5173/,http://localhost:5174/,http://localhost:4173,
server.port=${SERVER_PORT:7000}

springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=durbulemayu@gmail.com
spring.mail.password=qaulxpzdvlbjydwi
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

spring.security.oauth2.client.registration.google.client-id=113137334775-le1gso8sqiv08gue8du7cjglplnc8kec.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

